### ISSUE TITLE
http://kernelci.org/ lacks http->https redirect

### ISSUE THREAD

**Issue by kees** [kernelci/kernelci-frontend#120]
While the HTTPS site is configured with HSTS to make sure all https://kernelci.org/ visitors return to HTTPS by default, a first-time visitor who just types "kernelci.org" into their browser will connect over HTTP. Currently this displays the nginx welcome page ... it should automatically redirect to https://kernelci.org/ instead.

**Comment by gctucker** [comment]
That's right, good catch.  A simple way to reproduce the issue is with `curl`:
```
$ curl -I http://kernelci.org
HTTP/1.1 200 OK
Server: nginx
```

This should return a 302 instead to redirect to the HTTPS URL.  I believe most browsers already do that by themselves, by checking if there is a HTTPS URL available since I've never seen the issue on Firefox or Chromium.

I believe this needs to be fixed in https://github.com/kernelci/kernelci-frontend-config where the nginx config files are.

**Comment by kees** [comment]
> That's right, good catch. A simple way to reproduce the issue is with `curl`:
> 
> ```
> $ curl -I http://kernelci.org
> HTTP/1.1 200 OK
> Server: nginx
> ```
> 
> This should return a 302 instead to redirect to the HTTPS URL. I believe most browsers already do that by themselves, by checking if there is a HTTPS URL available since I've never seen the issue on Firefox or Chromium.

Well, the HSTS setting causes that (but requires that the person have visited the site once before), or if someone has the HTTPS-Everywhere plugin installed in their browser. Without either (as I just encountered on a fresh Chrome install on a new computer), one will see the nginx page. :)

**Comment by kees** [comment]
I've opened the new bug.
